services:
  auth-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - auth-net
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - auth-net

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - auth-net

networks:
  auth-net:
    driver: bridge